### ISSUE TITLE
Issues while adding to burp

### ISSUE THREAD

**Issue by jakre1234** [woodpecker-appstore/log4j-payload-generator#1]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.ftd.a(Unknown Source)
	at burp.ftd.<init>(Unknown Source)
	at burp.guy.a(Unknown Source)
	at burp.kp.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by c0ny1** [comment]
It is not a Burp Suite plug-in, but a [woodpecker-framework](https://github.com/woodpecker-framework/woodpecker-framwork-release/releases) plug-in

**Comment by x0d3** [comment]
so what is the solution ???
